#!/bin/sh
build :
	javac -cp lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar -d ./build src/java/*.java
build_test :
	javac -cp lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar:build -d ./build test/java/*.java
test :
	java -cp build/.:lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore EdgeConnectorTest
run :
	java -cp ./build/ RunEdgeConvert
clean :
	rm ./build/*.class
